### ISSUE TITLE
Setup Instructions

### ISSUE THREAD

**Issue by BenJamesAndo** [awkimball/mqtt-cec-appliance#2]
Hello. Just wondering how to get this working. Do I add it as a custom component in Home Assistant HACS? If so what do I do once I've uploaded the files?

I've got a raspberry pi 4 plugged into a TV with a HDMI cable. Home Assistant is running on a seperate machine.

**Comment by awkimball** [comment]
Hey Ben,

Sorry, but unfortunately I have neither the related Yamaha Receiver hardware nor a Raspberry Pi anymore so I won't be able to provide any further updates to this project.

I'm not sure how much (if any) the mqtt media player component has changed in Home Assistant over the past few years so this may or may not still work as-is.

In regards to your questions: as far as I recall, I manually added an mqtt-based media player to homeassistant's `configuration.yaml` but I will need to go check.

Best regards,
Addison

**Comment by awkimball** [comment]
Here's what I found as far as `configuration.yaml` goes:

```yaml
input_select:
    stereo_source:
        name: Stereo Source
        options:
          - "Airplay"
          - "TV"
          
media_player:
  - platform: universal
    name: house_stereo
    commands:
        turn_on: 
            service: switch.turn_on
            data: 
                entity_id: switch.stereo
        turn_off:
            service: switch.turn_off
            data: 
                entity_id: switch.stereo
        select_source:
            service: input_select.select_option
            data:
                entity_id: input_select.stereo_source
                option: "{{ source }}"
        volume_up:
            service: switch.turn_on
            data:
                entity_id: switch.volume
        volume_down:
            service: switch.turn_off
            data:
                entity_id: switch.volume
    attributes:
      state: switch.stereo
      source: input_select.stereo_source
      source_list: input_select.stereo_source|options
      volume_level: sensor.volume

sensor:
  - platform: systemmonitor
    resources:
      - type: network_out
        arg: eth0
  - platform: mqtt
    name: "volume"
    state_topic: "house/stereo/volume/state"
    value_template: "{{ value }}"

switch:
  - platform: mqtt
    name: stereo
    state_topic: "house/stereo/power/state"
    command_topic: "house/stereo/power/cmnd"
    availability_topic: "house/stereo/power/avail"
  - platform: mqtt
    name: volume
    command_topic: "house/stereo/volume/cmnd"
```

Again, not sure how much of this is still usable on current versions of HomeAssistant
